# Generated by Django 4.0.5 on 2022-07-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0005_product_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_per_100g',
            field=models.FloatField(blank=True, null=True, verbose_name='цена за 100гр'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='цена за 1кг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='цена'),
        ),
    ]
